name: serious_dating
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+2
  
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  flutter_facebook_auth: ^5.0.11
  twitter_login: ^4.4.0
  google_sign_in: ^6.1.2
  google_nav_bar: ^5.0.6
  google_fonts: ^4.0.4
  flutter_otp_text_field: ^1.1.1
  flutter_hooks: ^0.18.6
  get: ^4.6.5

  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icon/
    - assets/bg/
    - assets/dummy/
