name: serious_dating
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+2
  
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  flutter_facebook_auth: ^5.0.11
  twitter_login: ^4.4.0
  google_sign_in: ^6.1.2
  google_nav_bar: ^5.0.6
  google_fonts: ^4.0.4
  flutter_otp_text_field: ^1.1.1
  flutter_hooks: ^0.18.6
  shared_preferences: ^2.1.1
  flutter_screenutil: ^5.7.0
  cached_network_image: ^3.2.0
  pull_to_refresh: ^2.0.0
  lottie: ^2.3.1
  get: ^4.6.5
  firebase_storage: ^11.0.8
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/icon/
    - assets/bg/
    - assets/dummy/
